version: '3.8'

services:
  api:
    build: ./api
    container_name: express_api
    restart: always
    ports:
      - '3080:3080'
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/appdb
      - JWT_SECRET=algumasecreta
    depends_on:
      - db
    volumes:
      - ./api:/app
      - /app/node_modules
    command: sh -c "npm install && npm run start && node dist/index.js"

  app:
    build: ./client
    container_name: vite_app
    ports:
      - '3000:3000'
    depends_on:
      - api

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  selenium-test:
    image: seleniarm/node-chromium:latest
    working_dir: /tests
    volumes:
      - ./client/tests/e2e:/tests
      - ./client/package.json:/tests/package.json
      - ./client/package-lock.json:/tests/package-lock.json
    depends_on:
      - app
    entrypoint: >
      sh -c "npm install && npx jest --runInBand *.test.js"

volumes:
  pgdata:
