version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: artelocal
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build: ./api
    volumes:
      - ./api:/app
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - JWT_SECRET=segredo123
volumes:
  pgdata:
